name: behavioral-data-science
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - pip
  - python=3.12
  - matplotlib[version='>=3.10.0']
  - numpy~=1.26.3
  - scikit-learn[version='>=1.6.1']
  - scipy[version='>=1.15.1']
  - seaborn[version='>=0.13.2']
  - ipython[version='>=8.26.0']
  - ipywidgets[version='>=8.1.5']
  - notebook[version='>=7.3.2']
  - pip:
      - tensorflow>=2.17.0